import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/common/NavBar";
import { FooterPage } from "@/components/common/FooterPage";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className="w-screen min-h-screen flex flex-col no-scrollbar px-4 sm:px-12 md:px-16 lg:px-36 bg-gradient-to-r from-[#1f1f1f] to-[#131313] text-white">
					{/* Navbar */}
					<div className="h-24">
						<NavBar />
					</div>

					{/* Main Content */}
					<div className="flex-1">
						<div className="h-full">{children}</div>
					</div>

					{/* Footer */}
					<FooterPage />
				</div>
			</body>
		</html>
	);
}
